### ISSUE TITLE
Input center

### ISSUE THREAD

**Issue by FlorianBELLAZOUZ** [SebastianNette/PIXI.Input#2]
Hi !
Thanks for this amazing tool !

I have a probleme i can't center the text of an input.

Do you have code it ? or it's me who doing it wrong ?

``` javascript
var input = new PIXI.Input({
    align: "center",
    font:{
        align: "center",
    }
});

```

**Comment by SebastianNette** [comment]
Hi Florian,

sorry for not responding earlier.
You are right there is currently an issue with centering text.

There will soon be a new version of the input class to fix all the current issues.
This includes Textareas, fixed text positioning, overall cleaner code, less garbage production, etc.

**Comment by FlorianBELLAZOUZ** [comment]
Thanks for the repply !
I can't wait for this !

This will realy help me for my game project ( kaaarot.com).

Can i help you to release this faster ?

**Comment by FlorianBELLAZOUZ** [comment]
no reponse i close this issue.
