### ISSUE TITLE
what's the status of this?

### ISSUE THREAD

**Issue by andrevenancio** [SebastianNette/PIXI.Input#3]
Hey, I've just came across this as a solution for input text in pixi. doesnt work on latest pixi. what's the status? are you giving support? Is this deprecated?

**Comment by brean** [comment]
Hi André,
it is not working with PIXI v3 out-of-the-box. I forked it and made some quick adjustments to make it work:
https://github.com/brean/PIXI.Input

I am currently working on a UI-System for PIXI v3. The input field in my implementation does not have all features that PIXI.Input provides (yet) but if you are looking for a UI framework (with features like skinning and layout functionality) for PIXI check it out:
https://github.com/brean/pixi_ui

**Comment by SebastianNette** [comment]
HI Guys,

I have been really busy lately. I will look into your fork soon, @brean.
There is a lot room for improvement, I too have my own little UI framework which provides all kinds of dialogues (confirm, alert, prompts, etc), tables, sliders and more. I just can't find the time right now to work on it.

**Comment by andrevenancio** [comment]
thanks guys. in the meantime I've just created a quick implementation which creates a <input> on top of pixi, and I'm checking its position when the position in pixi.js changes.
